# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170817_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
